version: "3.8"
services:
  api:
    build:
      context: "."
      dockerfile: "./Dockerfile"
    container_name: "api-but-space"
    ports:
      - "8000:8000"
    networks:
      - "spaceify"
networks:
  spaceify:
    external: true
